@startuml Bahama Mama Telemetry Components

[Data Collector] as collector
[Data Composer] as composer
[FIFO] as fifo
[SD Interface] as sd
[ADC Collector] as adc
[GPS Collector] as gps

note top of fifo
    Use queue implementation
    from Pico SDK.
end note

note top of collector
    Run on Core 0.
end note

note top of composer
    Run on Core 1.
end note

collector -> fifo
fifo -> composer

collector -d-> adc
collector -d-> gps

composer -d-> sd

@enduml